### ISSUE TITLE
Create "shields" that could be embedded in websites

### ISSUE THREAD

**Issue by severo** [severo/tip_by_domain_renewal#1]
Something like https://shields.io/category/funding

or

![Expiration shield](https://img.shields.io/date/1583573886?color=%23fdbf05&label=Domain%20expires)

The problem is: how to get the color + expiration date? Client-side: it generates a lot of useless traffic. Server-side: it's complicated for the website maintainer. As a service (ie https://shield.payetondomaine.io/rezo.net): a service someone has to maintain.

**Comment by Fil** [comment]
Je ne suis pas trop pour — l'idée n'est pas de faire d'alourdir les sites ni de faire du donnant-donnant. On veut juste une interface qui permette de voir rapidement ce qu'on peut soutenir en priorité.
