### ISSUE TITLE
add a line "just renewed"

### ISSUE THREAD

**Issue by Fil** [severo/tip_by_domain_renewal#10]
for a domain with expiration > 365 days  && Updated Date < 1 week ?

**Comment by severo** [comment]
expiration > 358 days ?

**Comment by severo** [comment]
doesn't seem to work -> https://rednegra.net/payetondomaine/

**Comment by Fil** [comment]
arf—je corrige

**Comment by severo** [comment]
ça marche ! merci

**Comment by severo** [comment]
Hier les domaines visioncarto.net et visionscarto.net apparaissaient (356j et 365j avant expiration)

![Capture d’écran de 2020-01-15 09-08-37](https://user-images.githubusercontent.com/1676121/72508494-07ec1500-3846-11ea-8d26-34b39824b8f2.png)

Aujourd'hui ils ne sont plus dans la liste, mais ils n'apparaissent pas non plus dans les domaines récemment renouvelés.

![Capture d’écran de 2020-01-16 09-51-09](https://user-images.githubusercontent.com/1676121/72508340-ce1b0e80-3845-11ea-9693-6a6de9c59030.png)

**Comment by Fil** [comment]
non c'est parce que je l'ai supprimé de la liste https://github.com/severo/tip_by_domain_renewal/commit/ae40370abd8ce0cc0ae084583935084ad64d5538

**Comment by severo** [comment]
OK, j'aurais du regarder ça avant, pas pensé
