### ISSUE TITLE
Améliorer l'aide aux contributions

### ISSUE THREAD

**Issue by severo** [severo/tip_by_domain_renewal#4]
Si qqn veut proposer un nouveau domaine :
- expliquer clairement quels domaines peuvent être inclus ou pas
- donner la marche à suivre (PR, autre ?)
- appliquer un "hook" sur la PR pour s'assurer que le domaine existe, et est géré par Gandi

**Comment by Fil** [comment]
on peut ajouter quelque part une suggestion comme quoi on peut soutenir d'autres sites en faisant de même sans nécessairement que les sites soient dans notre liste.

**Comment by severo** [comment]
Fait dans le README
